### PR TITLE
Scoreboard Change and Score-Fix

### LINKED ISSUE #35: Resizing scoreboard duplicates current items

### PR DESCRIPTION
**Pull request by s1wegman**
#35

### CODE REVIEW

File: src/mainwindow.cpp [hunk 1]
```diff
@@ -108,9 +108,21 @@ void MainWindow::loadPage(MainWindow::Page p) {
 
 void MainWindow::addScore(Snake::Score s) {
     QString score = QString("%1 - ").arg(s.value, 6, 10, QLatin1Char('0'));
```
Comment (NaoPross) [inline src/mainwindow.cpp]:
```suggestion
    QString score = QString("%1 - ").arg(s.value, 6, 10, QLatin1Char('0')) + s.player;
```

File: src/mainwindow.cpp [hunk 2]
```diff
@@ -108,9 +108,21 @@ void MainWindow::loadPage(MainWindow::Page p) {
...
-    QListWidgetItem *item = new QListWidgetItem(score + s.player, ui->scoreboardListWidget);
-    unscii_font.setPointSize(15);
-    item->setFont(unscii_font);
+    if(!checkScoreboard(s, score)) {
+        QListWidgetItem *item = new QListWidgetItem(score + s.player, ui->scoreboardListWidget);
```
Comment (NaoPross) [inline src/mainwindow.cpp]:
```suggestion
    if(!checkScoreboard(score)) {
        QListWidgetItem *item = new QListWidgetItem(score, ui->scoreboardListWidget);
```

File: src/mainwindow.cpp [hunk 3]
```diff
@@ -108,9 +108,21 @@ void MainWindow::loadPage(MainWindow::Page p) {
...
+        unscii_font.setPointSize(15);
+        item->setFont(unscii_font);
+    }
+}
+
+bool MainWindow::checkScoreboard(Snake::Score s, QString score) {
```
Comment (NaoPross) [inline src/mainwindow.cpp]:
```suggestion
bool MainWindow::checkScoreboard(QString score) {
```

File: src/mainwindow.cpp [hunk 4]
```diff
@@ -108,9 +108,21 @@ void MainWindow::loadPage(MainWindow::Page p) {
...
+    bool found = false;
+    for (int i = 0; i < ui->scoreboardListWidget->count(); ++i) {
+        if(ui->scoreboardListWidget->item(i)->text() == (score + s.player)) {
```
Comment (NaoPross) [inline src/mainwindow.cpp]:
```suggestion
        if(ui->scoreboardListWidget->item(i)->text() == score) {
```

File: src/mainwindow.h [hunk 5]
```diff
@@ -43,6 +43,7 @@ public slots:
 
     bool loadScoreboard();
     bool writeScoreboard();
+    bool checkScoreboard(Snake::Score s, QString score);
```
Comment (NaoPross) [inline src/mainwindow.h]:
```suggestion
    bool checkScoreboard(QString score);
```

**Review by NaoPross — COMMENTED** [review]
Looks good! I'd just add this little change to make sure that it doesn't break if the formatting of score gets changed.
